{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.theunknowngroup",
    "module": "dalib",
    "version": "0.0.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dalib-0.0.0+1.21.11.jar",
          "url": "dalib-0.0.0+1.21.11.jar",
          "size": 11200,
          "sha512": "089b9a4957e58ccdffef0a3fdf5a473bd1c56df5f0d960826ecbf1b26e89c356739e724b52f7c35f1e13ff7169104e3bbf691b1a662726bc331f06b53dde1ddd",
          "sha256": "7a345e8ce20539e998702cc99342f019aed4b13fb1e53e62855f4310c6890572",
          "sha1": "ff54d52228a8d6645f3433a789e453c77bbaeea1",
          "md5": "6f481dea8591fedecf82e3cb068d2902"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "dalib-0.0.0+1.21.11.jar",
          "url": "dalib-0.0.0+1.21.11.jar",
          "size": 11200,
          "sha512": "089b9a4957e58ccdffef0a3fdf5a473bd1c56df5f0d960826ecbf1b26e89c356739e724b52f7c35f1e13ff7169104e3bbf691b1a662726bc331f06b53dde1ddd",
          "sha256": "7a345e8ce20539e998702cc99342f019aed4b13fb1e53e62855f4310c6890572",
          "sha1": "ff54d52228a8d6645f3433a789e453c77bbaeea1",
          "md5": "6f481dea8591fedecf82e3cb068d2902"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dalib-0.0.0+1.21.11-sources.jar",
          "url": "dalib-0.0.0+1.21.11-sources.jar",
          "size": 7764,
          "sha512": "85cf05fb46d38f8758a3ae0d95feaa2a258bbb98a40a2ca576a091b0202912937cea003f472dca97d3245624b7b679f38008fbd761cdb49aadc67e93d7b6ef32",
          "sha256": "9d46770ec3b18f65f9af64950fd33db9ad6104bf6b46ff659ba8e559df897582",
          "sha1": "03bb9dbc2bb797016020886d34e24e62e5cee158",
          "md5": "57df98c4c84da6801e0d94ca7ad5069e"
        }
      ]
    }
  ]
}
